version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: netbanking-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: netbanking
      MYSQL_USER: banking_user
      MYSQL_PASSWORD: banking_pass
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
